import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Off deliberately.
      //
      // It wants ' and " written as HTML entities inside JSX text. That guarded
      // against a real problem in much older React; today both render exactly
      // the same, and the rule has no auto-fix, so honouring it means hand-
      // editing prose in 29 places for no change in what anyone sees.
      //
      // The cost of leaving it on is worse than nothing: it was 29 of 112
      // errors, so a genuine crash sat in the same list — RefreshCw used
      // without an import — and nobody was going to find it in that noise.
      "react/no-unescaped-entities": "off",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by @ducanh2912/next-pwa on every build, minified, and not ours
    // to change. They accounted for 86 of 246 warnings — 70 of them a single
    // rule complaining about the comma expressions a minifier produces — so
    // every real warning was outnumbered three to one by output nobody writes.
    "public/sw.js",
    "public/workbox-*.js",
    "public/sw.js.map",
    "public/workbox-*.js.map",
  ]),
]);

export default eslintConfig;
