import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Off deliberately.
      //
      // It wants ' and " written as HTML entities inside JSX text. That guarded
      // against a real problem in much older React; today both render exactly
      // the same, and the rule has no auto-fix, so honouring it means hand-
      // editing prose in 29 places for no change in what anyone sees.
      //
      // The cost of leaving it on is worse than nothing: it was 29 of 112
      // errors, so a genuine crash sat in the same list — RefreshCw used
      // without an import — and nobody was going to find it in that noise.
      "react/no-unescaped-entities": "off",

      // Off, and this one is a judgement about the data rather than the rule.
      //
      // next/image is faster and lazy-loads, and it throws at runtime for any
      // host missing from images.remotePatterns — a 500 on the whole page, not
      // a broken thumbnail. Every one of the eight <img> tags it flagged points
      // at a URL this app does not control:
      //
      //   cafes.cover_url and cafe_images.image_url hold both
      //   *.supabase.co and lh3.googleusercontent.com, the latter arriving with
      //   Google Places data and not configured;
      //   HomeClient's membership and tournament tiles use images.unsplash.com;
      //   one has an onError fallback to via.placeholder.com, which next/image
      //   cannot express.
      //
      // So <img> fails softly on an unknown host and next/image takes the page
      // down with it. For URLs that come from users and third parties that is
      // the wrong trade, and listing hosts only holds until someone pastes a
      // link from a new one.
      //
      // Worth revisiting for images this app uploads itself, where the host is
      // known — that is a per-image decision, not a lint fix.
      "@next/next/no-img-element": "off",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by @ducanh2912/next-pwa on every build, minified, and not ours
    // to change. They accounted for 86 of 246 warnings — 70 of them a single
    // rule complaining about the comma expressions a minifier produces — so
    // every real warning was outnumbered three to one by output nobody writes.
    "public/sw.js",
    "public/workbox-*.js",
    "public/sw.js.map",
    "public/workbox-*.js.map",
  ]),
]);

export default eslintConfig;
