-- Migration: Remove hardcoded default password fallback from admin login
-- Description: verify_admin_login previously treated a NULL admin_password as
-- "admin123", letting anyone log in as any admin profile that never set a
-- password. Require an explicitly-set, matching password instead.
-- Author: Generated by Claude Code
-- Date: 2026-08-05

DROP FUNCTION IF EXISTS public.verify_admin_login(TEXT, TEXT);

CREATE FUNCTION public.verify_admin_login(
  p_username TEXT,
  p_password TEXT
)
RETURNS TABLE (
  user_id UUID,
  username TEXT,
  is_valid BOOLEAN
)
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id as user_id,
    p.admin_username as username,
    (
      p.admin_password IS NOT NULL AND
      p.admin_password = p_password AND
      (p.is_admin = true OR p.role IN ('admin', 'super_admin'))
    ) as is_valid
  FROM public.profiles p
  WHERE p.admin_username = p_username
  LIMIT 1;
END;
$$;

GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO service_role;

COMMENT ON FUNCTION public.verify_admin_login IS 'Securely verify admin login credentials without exposing password in response';
